# Site settings
title: Wesley Abbey
header-img: img/home-bg.jpg
email: wesleyabbey.io@gmail.com
copyright_name: Wesley Abbey
description: "I'm Wesley! By night I'm Batman, but when I'm not fighting crime I'm usually programing at Wayfair or doing a handstand"
baseurl: ""
url: "http://www.wesleyabbey.com"
twitter_username: wesleyabbey
github_username: wesleyabbey
facebook_username: wesleyabbey
instagram_username: wesleyabbey.io
email_username:  wesleyabbey.io@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
