# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wesley Abbey
mail: wesleyabbey.io@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the current webpage for Wesley Abbey. He is currently taking his sweet time to actually get this site an actual design and legitamate layout.
  He will, hopefully be fixing this very soon.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.wesleyabbey.com" # the base hostname & protocol for your site
twitter_username: wesleyabbey 
github_username:  wesleyabbey

# Build settings
markdown: kramdown
